spring:
  datasource:
    url: jdbc:mysql://localhost:8889/Fullstack+Exercise
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect